# Development environment variables
env_name: "dev"
app_dir: "/opt/sportspuff-v6-dev"
service_name: "sportspuff-v6-dev"
app_port: 34181
branch: "dev"
flask_env: "development"
flask_debug: "True"
sportspuff_api_base_url: "https://api-dev.sportspuff.org"
