# Production environment variables
env_name: "prod"
app_dir: "/opt/sportspuff-v6-prod"
service_name: "sportspuff-v6-prod"
app_port: 34080
branch: "main"
flask_env: "production"
flask_debug: "False"
sportspuff_api_base_url: "https://api.sportspuff.org"
